CREATE DATABASE FISE
USE FISE
CREATE TABLE OBRA(
CODIGO			INT														NOT NULL,
TITULO			VARCHAR(40)												NOT NULL,
DATAA			DATE													NOT NULL,
AVALIACAO		INT														NOT NULL,
TPOBRA			CHAR(01)		CHECK(TPOBRA = 'S' OR TPOBRA = 'F')		NOT NULL
PRIMARY KEY (CODIGO,TPOBRA)
)

CREATE TABLE GENERO(
GCODIGO			INT														NOT NULL,
GTPOBRA			CHAR(01)		CHECK(GTPOBRA = 'S' OR GTPOBRA = 'F')	NOT NULL,
TPGENERO		VARCHAR(30)												NOT NULL
PRIMARY KEY (GCODIGO,GTPOBRA,TPGENERO)
FOREIGN KEY (GCODIGO,GTPOBRA)
			REFERENCES OBRA
)

CREATE TABLE SERIE(
SCODIGO			INT								NOT NULL,
STPOBRA			CHAR(01) CHECK(STPOBRA = 'S')	NOT NULL,
NUMTEMP			INT								NOT NULL
PRIMARY KEY (SCODIGO,STPOBRA)
FOREIGN KEY (SCODIGO,STPOBRA)
			REFERENCES OBRA
)
--------------------------------------------------------------------------------------------------------------
CREATE TABLE ATOR(
ACODIGO			INT														NOT NULL,
NOME			VARCHAR(40)												NOT NULL,
NOMEART			VARCHAR(40)												NOT NULL,
NACIONALIDADE	VARCHAR(20)												NOT NULL,
--ATPPESSOA		CHAR(01)	CHECK(ATPPESSOA = 'A')						NOT NULL
PRIMARY KEY (ACODIGO)
--FOREIGN KEY (ACODIGO,ATPPESSOA)
			--REFERENCES PESSOA
)
CREATE TABLE ATOR_OBRA(
ACODIGO			INT														NOT NULL,
--ATPPESSOA		CHAR(01)	CHECK(ATPPESSOA = 'A')						NOT NULL,
OCODIGO			INT														NOT NULL,
OTPOBRA			CHAR(01) CHECK(OTPOBRA = 'F' OR OTPOBRA = 'S')			NOT NULL
PRIMARY KEY (ACODIGO,OCODIGO,OTPOBRA)
FOREIGN KEY (OCODIGO,OTPOBRA)
			REFERENCES OBRA,
FOREIGN KEY (ACODIGO)
			REFERENCES ATOR (ACODIGO)
)
CREATE TABLE CLIENTE(
CCODIGO			INT														NOT NULL,
NOME			VARCHAR(40)												NOT NULL,
CPF				VARCHAR(11)	CHECK(LEN(CPF) = 11)						NOT NULL,
RG				VARCHAR(9)	CHECK(LEN(RG) = 9)							NOT NULL,
EMAIL			VARCHAR(40)												NOT NULL,
TELEFONE		VARCHAR(11)												NOT NULL
PRIMARY KEY (CCODIGO)
)
DROP TABLE CLIENTE_PLANO
DROP TABLE CLIENTE
DROP TABLE PESSOA
DROP TABLE ATOR
DROP TABLE ATOR_OBRA

CREATE TABLE CLIENTE_PLANO(
PCCODIGO		INT										NOT NULL,
PNOME			VARCHAR(40)								NOT NULL,
DATAI			DATE									NOT NULL,			
DATAF			DATE									NOT NULL
PRIMARY KEY (PCCODIGO)
FOREIGN KEY (PNOME)
			REFERENCES PLANO (NOME),
FOREIGN KEY (PCCODIGO)
			REFERENCES CLIENTE (CCODIGO)
)
DROP TABLE CLIENTE_PLANO
DROP TABLE PLANO
CREATE TABLE PLANO(
NOME			VARCHAR(40)				NOT NULL,
PERIODO			VARCHAR(12)				NOT NULL,
OAVALIACAO		INT						NOT NULL,
QUANT			INT						NOT NULL,
VQUALIDADE		VARCHAR(40)				NOT NULL,
PRECO			NUMERIC(7,2)			NOT NULL,	
TPOBRA			CHAR(01)	CHECK(TPOBRA = 'S' OR TPOBRA = 'F' OR TPOBRA = 'D')		NOT NULL
PRIMARY KEY (NOME)
)
CREATE TABLE TEMPORADA(
OCODIGO			INT									NOT NULL,
TPOBRA			CHAR(01) CHECK(TPOBRA = 'S')		NOT NULL,
TNUM			INT									NOT NULL,
TOTEP			INT									NOT NULL
PRIMARY KEY (OCODIGO,TPOBRA,TNUM)
FOREIGN  KEY (OCODIGO,TPOBRA)
			REFERENCES OBRA
)
CREATE TABLE EPSODIO(
EPNUM			INT				NOT NULL,
TNUM			INT				NOT NULL,
OCODIGO			int				NOT NULL,
TPOBRA			VARCHAR(01) CHECK(TPOBRA = 'S')		NOT NULL,
TITULO			VARCHAR(40)		NOT NULL,
DURACAO			TIME			NOT NULL
PRIMARY KEY (OCODIGO,TPOBRA,TNUM,EPNUM)
)

CREATE TABLE CATALOGO(
PNOME			VARCHAR(40)											NOT NULL,
OCODIGO			INT													NOT NULL,
TPOBRA			CHAR												NOT NULL
PRIMARY KEY (PNOME,OCODIGO,TPOBRA)
FOREIGN KEY (PNOME)
			REFERENCES PLANO (NOME),
FOREIGN KEY (OCODIGO,TPOBRA)
			REFERENCES OBRA 
)
DROP TABLE CATALOGO

SELECT * FROM ATOR_OBRA
SELECT * FROM OBRA
SELECT * FROM ATOR
SELECT * FROM PESSOA
SELECT * FROM CLIENTE
SELECT C.CCODIGO,C.NOME,C.CPF,C.RG,C.EMAIL,C.TELEFONE FROM CLIENTE C
SELECT * FROM ATOR A
SELECT A.ACODIGO,A.NOME,A.NOMEART,A.NACIONALIDADE FROM ATOR A

SELECT * FROM PLANO

--SELECT DATEADD(DAY,GETDATE(),30) FROM CLIENTE
SELECT * FROM CLIENTE_PLANO
SELECT CP.PCCODIGO,CP.PNOME, CP.DATAI, CP.DATAF FROM CLIENTE_PLANO CP 


SELECT * FROM OBRA
SELECT O.CODIGO,O.TITULO FROM OBRA O WHERE TPOBRA = 'F'
SELECT O.CODIGO,O.TITULO FROM OBRA O WHERE TPOBRA = 'S'

SELECT O.CODIGO,O.TITULO FROM OBRA O WHERE TPOBRA = 'S' 

SELECT O.CODIGO,O.TITULO,O.TPOBRA,O.AVALIACAO FROM OBRA O WHERE TPOBRA = 'F' 

SELECT O.CODIGO,O.TITULO,O.TPOBRA,O.AVALIACAO FROM OBRA O WHERE TPOBRA = 'S' 

SELECT * FROM CATALOGO

SELECT CAT.PNOME,CAT.OCODIGO,O.TITULO,O.AVALIACAO,O.TPOBRA 
FROM CATALOGO CAT INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND O.TPOBRA = CAT.TPOBRA
WHERE CAT.PNOME = 'brand' AND O.AVALIACAO <= 5 AND O.TPOBRA = 'F'

DELETE FROM CATALOGO WHERE PNOME = 'AGARASUPERGUN'


SELECT * FROM OBRA

INSERT INTO CATALOGO VALUES ('brand',99,'F')

SELECT * FROM CATALOGO 

DELETE CAT FROM CATALOGO CAT 
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND CAT.TPOBRA = O.TPOBRA
WHERE CAT.PNOME = 'brand' AND O.AVALIACAO > 5

SELECT * FROM CATALOGO CAT
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND CAT.TPOBRA = O.TPOBRA
INNER JOIN PLANO P ON P.NOME = CAT.PNOME
WHERE O.CODIGO = 44 AND O.TPOBRA = 'F' AND O.AVALIACAO < P.OAVALIACAO 

SELECT COUNT(P.NOME) AS TOT FROM PLANO P
INNER JOIN CATALOGO CAT ON CAT.PNOME = P.NOME
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND O.TPOBRA = CAT.TPOBRA
WHERE P.NOME = 'bsdsd'
GROUP BY P.NOME
ORDER BY O.AVALIACAO ASC

SELECT * FROM PLANO P
INNER JOIN CATALOGO CAT ON CAT.PNOME = P.NOME
WHERE P.NOME = 'brand'

SELECT CAT.PNOME,CAT.OCODIGO,CAT.TPOBRA FROM CATALOGO CAT
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND CAT.TPOBRA = O.TPOBRA
WHERE CAT.PNOME = 'brand'
ORDER BY O.AVALIACAO ASC

DELETE CAT FROM CATALOGO CAT
WHERE CAT.PNOME = 'brand' AND CAT.OCODIGO  = 99 AND TPOBRA = 'F'

DELETE CAT FROM CATALOGO CAT
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND CAT.TPOBRA = O.TPOBRA
WHERE O.CODIGO = 44 AND O.TPOBRA = 'F'

SELECT CAT.PNOME,CAT.OCODIGO,CAT.TPOBRA FROM CATALOGO CAT
INNER JOIN OBRA O ON O.CODIGO = CAT.OCODIGO AND CAT.TPOBRA = O.TPOBRA
WHERE CAT.PNOME = 'brand'
ORDER BY O.AVALIACAO ASC 